# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-02 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stt_de', models.CharField(blank=True, max_length=8, null=True)),
                ('stt_tm', models.CharField(blank=True, max_length=4, null=True)),
                ('site', models.CharField(blank=True, max_length=50, null=True)),
                ('keyword', models.CharField(blank=True, max_length=50, null=True)),
                ('rk', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'item_rank',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=20, null=True)),
                ('site', models.CharField(blank=True, max_length=50, null=True)),
                ('keyword', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'item_site',
                'managed': False,
            },
        ),
    ]
